services:
  todo-backend:
    container_name: todo-backend
    image: virajsh/todo-backend:latest
    ports:
      - 8888:80
    env_file:
      - backend/.env
    networks:
      - nginx
  todo-frontend:
    container_name: todo-frontend
    image: virajsh/todo-frontend:latest
    ports:
      - 5173:80
    env_file:
      - frontend/.env
    
    networks:
      - nginx
  mongo:
    container_name: todo-database
    image: mongo:8.3.2
    ports:
      - 20000:27017
    env_file:
      - .env
    
    networks:
      - nginx
networks:
  nginx: